################################################################################# 
# Author:FS
# Date: 2021
# Copyright: Agustin Bassi (https://github.com/agustinBassi/mq-connection)
# License: MIT
# Project: Node-project - Start coding IALAB
#################################################################################
  
version: '3.8'

services:
  postgres:

    container_name:          postgres

    image:                   postgres:latest # use latest official postgres version
    
    environment:
      POSTGRES_DB:           nodejs-course
      POSTGRES_USER:         postgres                                     
      POSTGRES_PASSWORD:     pass
      TZ:                    America/Argentina/Buenos_Aires  

    volumes:
                            #Copy the sql script to create tables
      -                     ./db/dumps/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      -                     ./db/data:/var/lib/postgresql/data/ # persist data even if container shuts down 
    ports:  
      -                      "5432:5432"

  pgAdmin:
    
    depends_on:             
      -                      postgres
    
    image:                   dpage/pgadmin4:latest

    restart:                  always
    
    environment:
      PGADMIN_DEFAULT_EMAIL:    admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT:      5050
        
    ports:
      -                       "5050:5050"